### ISSUE TITLE
Add examples for heart rate monitor & GATT dump

### ISSUE THREAD

**Issue by tdicola** [adafruit/Adafruit_Python_BluefruitLE#1]
Add examples (and services where required) for a heart rate monitor and dump of all GATT attributes, etc.

**Comment by transfluxus** [comment]
can someone provide code for that?

**Comment by mfferreira** [comment]
bump

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
