### ISSUE TITLE
Ctrl-C doesn't interrupt list_uarts.py on OSX 10.9.5

### ISSUE THREAD

**Issue by tferrin** [adafruit/Adafruit_Python_BluefruitLE#12]
list_uarts.py never exits even after Ctrl-C is typed. The "while True" loop in list_uarts continues to run once per second and the "except KeyboardInterrupt" clause in corebluetooth/provider.py is never executed.  Sending other signals to the process (e.g. HUP, TERM) cause it to exit, but not SIGINT.  This is with the standard Apple supplied python 2.7.5 that comes with OSX 10.9.5.

**Comment by zapa1928** [comment]
On Raspbian Strech it also doesn't stop on Ctrl-C

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
