### ISSUE TITLE
very slow response

### ISSUE THREAD

**Issue by timredfern** [adafruit/Adafruit_Python_BluefruitLE#21]
I'm trying to log data from a notify characteristic that publishes a 4 byte number 15 times per second.

The library does kind of work, but:

-there is a ~10 second delay before initially receiving a notification after subscribing
-notifications arrive erratically in bunches of 2 or 3 about every second - so I guess most must be discarded

I'm using OSX sierra on a mac book pro.

I've seen similar performance in linux.

Without looking into it deeply, is this a limitation of desktop BLE libraries or in the implementation?

**Comment by luopio** [comment]
I'm seeing similar performance problems also on a mac. Using a sensor that transmits 100 12bit packages per second (works just fine on Android):
```
Waiting up to 60 seconds to receive data from the device...
>> 1.51693334042 packets per second
>> 6.69153234716 packets per second
>> 6.67559440157 packets per second
>> 5.01419869372 packets per second
```

Anything that could be done to increase the throughput?

**Comment by luopio** [comment]
Disregard my comment. After further trials with a node-based solution the problem was found in the firmware of the device, which dropped from 100hz to 5hz after ~1 second of operation. After fixing that I'm seeing 100Hz with both Node and Python.

**Comment by gilduz** [comment]
I have a similar issue with my BLE device, but the firmware is ok. I'm able to stream in android and ios 19 byte characteristic at ~120 Hz. Using this library I'm missing really a lot of packets. I'm on MacOS. Any chance to find a solution?

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
