### ISSUE TITLE
no module named 'dbus'

### ISSUE THREAD

**Issue by mjsir911** [adafruit/Adafruit_Python_BluefruitLE#41]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  
```
$ uname -a
Linux Ridl3y 4.19.27-gentoo-r1 #1 SMP Tue Mar 19 20:10:14 EDT 2019 x86_64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz GenuineIntel GNU/Linux
```

- Python version (run `python -version` or `python3 -version`):  
```
$ python3 --version
Python 3.6.5
```

- Error message you are receiving, including any Python exception traces: 
```
$ python3 list_uarts.py 
Traceback (most recent call last):
  File "list_uarts.py", line 11, in <module>
    ble = Adafruit_BluefruitLE.get_provider()
  File "/home/msirabella/Documents/projects/blueduck/venv/lib/python3.6/site-packages/Adafruit_BluefruitLE/platform.py", line 38, in get_provider
    from .bluez_dbus.provider import BluezProvider
  File "/home/msirabella/Documents/projects/blueduck/venv/lib/python3.6/site-packages/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 29, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

- List the steps to reproduce the problem below (if possible attach code or commands
  to run):
    * install library in virtual environment
    ```$ pip install git+http://github.com/adafruit/Adafruit_Python_BluefruitLE.git```
    * clone repository
    ```$ git clone git@github.com:adafruit/Adafruit_Python_BluefruitLE.git```
    * run example
    ```$ python3 Adafruit_Python_BluefruitLE/examples/list_uarts.py```

```$ pip install dbus-python``` fixed this issue

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
