### ISSUE TITLE
Exceptions are platform specific

### ISSUE THREAD

**Issue by ashesman** [adafruit/Adafruit_Python_BluefruitLE#45]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  Ubuntu 18

- Python version (run `python -version` or `python3 -version`):  3.5

- Error message you are receiving, including any Python exception traces:  dbus.exceptions.DBusException not handled by library

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): 

adapter = ble.get_default_adapter()
adapter.power_on()
adapter.start_scan()
  ... find devices
adapter.stop_scan()   <--- Sometimes raises a dbus.exceptions.DBusException

dbus exceptions should not make it to the application interface as are platform (linux) specific right?  They should be converted to a library specific or generic exception type.  Now my application exception handling code needs to import and handle dbus exception types.

Thanks for the handly library, still the best option around IMO...

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
