### ISSUE TITLE
Download error when installed on Mac OS 10.11

### ISSUE THREAD

**Issue by timur-tabi** [adafruit/Adafruit_Python_BluefruitLE#46]
I cloned the git repository and installed using the directions provided, but I ran into multiple errors:

$ sudo python setup.py install
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating Adafruit_BluefruitLE.egg-info
writing requirements to Adafruit_BluefruitLE.egg-info/requires.txt
writing Adafruit_BluefruitLE.egg-info/PKG-INFO
writing top-level names to Adafruit_BluefruitLE.egg-info/top_level.txt
writing dependency_links to Adafruit_BluefruitLE.egg-info/dependency_links.txt
writing manifest file 'Adafruit_BluefruitLE.egg-info/SOURCES.txt'
reading manifest file 'Adafruit_BluefruitLE.egg-info/SOURCES.txt'
writing manifest file 'Adafruit_BluefruitLE.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-intel/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/Adafruit_BluefruitLE
copying Adafruit_BluefruitLE/__init__.py -> build/lib/Adafruit_BluefruitLE
copying Adafruit_BluefruitLE/config.py -> build/lib/Adafruit_BluefruitLE
copying Adafruit_BluefruitLE/platform.py -> build/lib/Adafruit_BluefruitLE
creating build/lib/Adafruit_BluefruitLE/bluez_dbus
copying Adafruit_BluefruitLE/bluez_dbus/__init__.py -> build/lib/Adafruit_BluefruitLE/bluez_dbus
copying Adafruit_BluefruitLE/bluez_dbus/adapter.py -> build/lib/Adafruit_BluefruitLE/bluez_dbus
copying Adafruit_BluefruitLE/bluez_dbus/device.py -> build/lib/Adafruit_BluefruitLE/bluez_dbus
copying Adafruit_BluefruitLE/bluez_dbus/gatt.py -> build/lib/Adafruit_BluefruitLE/bluez_dbus
copying Adafruit_BluefruitLE/bluez_dbus/provider.py -> build/lib/Adafruit_BluefruitLE/bluez_dbus
creating build/lib/Adafruit_BluefruitLE/corebluetooth
copying Adafruit_BluefruitLE/corebluetooth/__init__.py -> build/lib/Adafruit_BluefruitLE/corebluetooth
copying Adafruit_BluefruitLE/corebluetooth/adapter.py -> build/lib/Adafruit_BluefruitLE/corebluetooth
copying Adafruit_BluefruitLE/corebluetooth/device.py -> build/lib/Adafruit_BluefruitLE/corebluetooth
copying Adafruit_BluefruitLE/corebluetooth/gatt.py -> build/lib/Adafruit_BluefruitLE/corebluetooth
copying Adafruit_BluefruitLE/corebluetooth/metadata.py -> build/lib/Adafruit_BluefruitLE/corebluetooth
copying Adafruit_BluefruitLE/corebluetooth/objc_helpers.py -> build/lib/Adafruit_BluefruitLE/corebluetooth
copying Adafruit_BluefruitLE/corebluetooth/provider.py -> build/lib/Adafruit_BluefruitLE/corebluetooth
creating build/lib/Adafruit_BluefruitLE/interfaces
copying Adafruit_BluefruitLE/interfaces/__init__.py -> build/lib/Adafruit_BluefruitLE/interfaces
copying Adafruit_BluefruitLE/interfaces/adapter.py -> build/lib/Adafruit_BluefruitLE/interfaces
copying Adafruit_BluefruitLE/interfaces/device.py -> build/lib/Adafruit_BluefruitLE/interfaces
copying Adafruit_BluefruitLE/interfaces/gatt.py -> build/lib/Adafruit_BluefruitLE/interfaces
copying Adafruit_BluefruitLE/interfaces/provider.py -> build/lib/Adafruit_BluefruitLE/interfaces
creating build/lib/Adafruit_BluefruitLE/services
copying Adafruit_BluefruitLE/services/__init__.py -> build/lib/Adafruit_BluefruitLE/services
copying Adafruit_BluefruitLE/services/colorific.py -> build/lib/Adafruit_BluefruitLE/services
copying Adafruit_BluefruitLE/services/device_information.py -> build/lib/Adafruit_BluefruitLE/services
copying Adafruit_BluefruitLE/services/servicebase.py -> build/lib/Adafruit_BluefruitLE/services
copying Adafruit_BluefruitLE/services/uart.py -> build/lib/Adafruit_BluefruitLE/services
creating build/bdist.macosx-10.11-intel
creating build/bdist.macosx-10.11-intel/egg
creating build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE
copying build/lib/Adafruit_BluefruitLE/__init__.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE
creating build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/bluez_dbus
copying build/lib/Adafruit_BluefruitLE/bluez_dbus/__init__.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/bluez_dbus
copying build/lib/Adafruit_BluefruitLE/bluez_dbus/adapter.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/bluez_dbus
copying build/lib/Adafruit_BluefruitLE/bluez_dbus/device.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/bluez_dbus
copying build/lib/Adafruit_BluefruitLE/bluez_dbus/gatt.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/bluez_dbus
copying build/lib/Adafruit_BluefruitLE/bluez_dbus/provider.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/bluez_dbus
copying build/lib/Adafruit_BluefruitLE/config.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE
creating build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth
copying build/lib/Adafruit_BluefruitLE/corebluetooth/__init__.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth
copying build/lib/Adafruit_BluefruitLE/corebluetooth/adapter.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth
copying build/lib/Adafruit_BluefruitLE/corebluetooth/device.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth
copying build/lib/Adafruit_BluefruitLE/corebluetooth/gatt.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth
copying build/lib/Adafruit_BluefruitLE/corebluetooth/metadata.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth
copying build/lib/Adafruit_BluefruitLE/corebluetooth/objc_helpers.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth
copying build/lib/Adafruit_BluefruitLE/corebluetooth/provider.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth
creating build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/interfaces
copying build/lib/Adafruit_BluefruitLE/interfaces/__init__.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/interfaces
copying build/lib/Adafruit_BluefruitLE/interfaces/adapter.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/interfaces
copying build/lib/Adafruit_BluefruitLE/interfaces/device.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/interfaces
copying build/lib/Adafruit_BluefruitLE/interfaces/gatt.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/interfaces
copying build/lib/Adafruit_BluefruitLE/interfaces/provider.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/interfaces
copying build/lib/Adafruit_BluefruitLE/platform.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE
creating build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/services
copying build/lib/Adafruit_BluefruitLE/services/__init__.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/services
copying build/lib/Adafruit_BluefruitLE/services/colorific.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/services
copying build/lib/Adafruit_BluefruitLE/services/device_information.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/services
copying build/lib/Adafruit_BluefruitLE/services/servicebase.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/services
copying build/lib/Adafruit_BluefruitLE/services/uart.py -> build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/services
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/bluez_dbus/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/bluez_dbus/adapter.py to adapter.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/bluez_dbus/device.py to device.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/bluez_dbus/gatt.py to gatt.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/bluez_dbus/provider.py to provider.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/config.py to config.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth/adapter.py to adapter.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth/device.py to device.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth/gatt.py to gatt.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth/metadata.py to metadata.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth/objc_helpers.py to objc_helpers.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/corebluetooth/provider.py to provider.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/interfaces/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/interfaces/adapter.py to adapter.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/interfaces/device.py to device.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/interfaces/gatt.py to gatt.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/interfaces/provider.py to provider.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/platform.py to platform.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/services/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/services/colorific.py to colorific.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/services/device_information.py to device_information.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/services/servicebase.py to servicebase.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/Adafruit_BluefruitLE/services/uart.py to uart.pyc
creating build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying Adafruit_BluefruitLE.egg-info/PKG-INFO -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying Adafruit_BluefruitLE.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying Adafruit_BluefruitLE.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying Adafruit_BluefruitLE.egg-info/requires.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying Adafruit_BluefruitLE.egg-info/top_level.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/Adafruit_BluefruitLE-0.9.10-py2.7.egg' and adding 'build/bdist.macosx-10.11-intel/egg' to it
removing 'build/bdist.macosx-10.11-intel/egg' (and everything under it)
Processing Adafruit_BluefruitLE-0.9.10-py2.7.egg
Copying Adafruit_BluefruitLE-0.9.10-py2.7.egg to /Library/Python/2.7/site-packages
Adding Adafruit-BluefruitLE 0.9.10 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/Adafruit_BluefruitLE-0.9.10-py2.7.egg
Processing dependencies for Adafruit-BluefruitLE==0.9.10
Searching for pyobjc-framework-CoreBluetooth
Reading https://pypi.python.org/simple/pyobjc-framework-CoreBluetooth/
Download error on https://pypi.python.org/simple/pyobjc-framework-CoreBluetooth/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'pyobjc-framework-CoreBluetooth' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
No local packages or download links found for pyobjc-framework-CoreBluetooth
error: Could not find suitable distribution for Requirement.parse('pyobjc-framework-CoreBluetooth')

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
