### ISSUE TITLE
Cannot run this with Python 3.7

### ISSUE THREAD

**Issue by mariedilworth** [adafruit/Adafruit_Python_BluefruitLE#47]
Lots of issues encountered trying to run this with Python 3.7

**Comment by AEDWIP** [comment]
At Least on Mac. Lot of problems went away when used pip uninstall the remove the pypi version and installed the version from github master

It still does not work

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
