### ISSUE TITLE
UART.find_devices() returns empty list

### ISSUE THREAD

**Issue by pvanallen** [adafruit/Adafruit_Python_BluefruitLE#50]
In the same configuration, find_device() returns the first CPB correctly. What I want to be able to do is to run this in a classroom full of CPBs where each student names theirs differently. And so the version running on their computer/RPi gets the correct device by checking the name.

MacOS 10.15.2
Python 3.7.4

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
