### ISSUE TITLE
trouble running examples on mac OS

### ISSUE THREAD

**Issue by aedavids** [adafruit/Adafruit_Python_BluefruitLE#51]
I am new to BLE and Bluetooth.  I am not able to run the examples. They never output anything useful? They never seem to find any peripherals 

```
(macBLETest) $ python Adafruit_Python_BluefruitLE/examples/list_uarts.py 
Using adapter: Default Adapter
Searching for UART devices...
Press Ctrl-C to quit (will take ~30 seconds on OSX).
^C(macBLETest) $ 
```

To try and debug this. I used the example from the blog post [https://punchthrough.com/bluetooth-low-energy-peripheral-testing/ ](https://punchthrough.com/bluetooth-low-energy-peripheral-testing/) . It shows how to use their iOS Lightblue to create a virtual device that their BluefruitLE test python scripts is able to read and write to. 

for unknown reasons, the BluefruitLE example do not seem to find the virtual device or any of my real devices. 

## My env
- mac os Mojave 10.14.6 (18G2022)
- Python 3.7.5

## Installation process
the version in pypi seems out of date. It  rasies NSExceptions
```
(base) $ conda activate macBLETest
(macBLETest) $ pwd
~/macBLETest/Adafruit_Python_BluefruitLE
(macBLETest) $ git clone https://github.com/adafruit/Adafruit_Python_BluefruitLE.git
(macBLETest) $ python setup.py install
(macBLETest) $ pip install pyobjc
```

Kind regards

Andy

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
