### ISSUE TITLE
device.rssi gives error: No such property 'RSSI'

### ISSUE THREAD

**Issue by aborger** [adafruit/Adafruit_Python_BluefruitLE#52]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

- Python version (run `python -version` or `python3 -version`):  Python 2.7.16

- Error message you are receiving, including any Python exception traces:  Traceback (most recent call last):
  File "getRSSI.py", line 80, in <module>
    ble.run_mainloop_with(main)
  File "build/bdist.linux-armv7l/egg/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 105, in run_mainloop_with
  File "build/bdist.linux-armv7l/egg/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 120, in _user_thread_main
  File "getRSSI.py", line 63, in main
    rssi = device.rssi
  File "build/bdist.linux-armv7l/egg/Adafruit_BluefruitLE/bluez_dbus/device.py", line 161, in rssi
  File "/usr/local/lib/python2.7/dist-packages/dbus/proxies.py", line 147, in __call__
    **keywords)
  File "/usr/local/lib/python2.7/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such property 'RSSI'

- List the steps to reproduce the problem below (if possible attach code or commands
  to run):

Program is an adaptation of the low_level.py example:
*****************************************************************************************************

import Adafruit_BluefruitLE
from Adafruit_BluefruitLE.services import UART
import uuid
import time

# Get the BLE provider for the current platform.
ble = Adafruit_BluefruitLE.get_provider()

# Main function implements the program logic so it can run in a background
# thread.  Most platforms require the main thread to handle GUI events and other
# asyncronous events like BLE actions.  All of the threading logic is taken care
# of automatically though and you just need to provide a main function that uses
# the BLE provider.
def main():
    # Clear any cached data because both bluez and CoreBluetooth have issues with
    # caching data and it going stale.
    ble.clear_cached_data()

    # Get the first available BLE network adapter and make sure it's powered on.
    adapter = ble.get_default_adapter()
    adapter.power_on()
    print('Using adapter: {0}'.format(adapter.name))
 # Disconnect any currently connected UART devices.  Good for cleaning up and
    # starting from a fresh state.
    print('Disconnecting any connected UART devices...')
    UART.disconnect_devices()

    # Scan for UART devices.
    print('Searching for UART device...')
    try:
        adapter.start_scan()
        # Search for the first UART device found (will time out after 60 seconds
        # but you can specify an optional timeout_sec parameter to change it).
        device = UART.find_device()
        if device is None:
            raise RuntimeError('Failed to find UART device!')
    finally:
  # Make sure scanning is stopped before exiting.
        adapter.stop_scan()

    print('Connecting to device...')
    device.connect()  # Will time out after 60 seconds, specify timeout_sec parameter
                      # to change the timeout.

    # Once connected do everything else in a try/finally to make sure the device
    # is disconnected when done.
    try:
        print('Getting device info...')
        # device.is_connected and device.name work successfully
        connection = device.is_connected
        name = device.name
 print ('Connection: ')
        print (connection)
        print ('Name: ')
        print (name)
        try:
                rssi = device.rssi #error occurs here
                print ('RSSI: ')
                print (rssi)
        finally:
                pass
    finally:
        print('Disconnecting...')
        # Make sure device is disconnected on exit.
# Initialize the BLE system.  MUST be called before other BLE calls!
ble.initialize()

# Start the mainloop to process BLE events, and run the provided function in
# a background thread.  When the provided main function stops running, returns
# an integer status code, or throws an error the program will exit.
ble.run_mainloop_with(main)

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
