### ISSUE TITLE
General question, what thread is CoreBluetooth running on?

### ISSUE THREAD

**Issue by seanngpack** [adafruit/Adafruit_Python_BluefruitLE#53]
^ title. 

In the documentation for run_mainloop_with():
```
        If you are writing a GUI application that has a main loop (a GTK glib main loop
        on Linux, or a Cocoa main loop on OSX) then you don't need to call this
        function.
```

So in my application, I didn't need to call run_mainloop_with to work, and I simply initialized it with
```
 self.ble = Adafruit_BluefruitLE.get_provider()
 self.ble.initialize()
```
in my main thread...however what thread is CoreBluetooth (the underlying wrapped library) using? I thought CoreBluetooth needed to be run on the main thread for its callbacks to work?

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
